### ISSUE TITLE
Hot-reloading doesn't trigger for imported files

### ISSUE THREAD

**Issue by kodie** [fivefifteen/piler#1]
For example if I have:

`style.scss`:
```scss
@import 'button';
```

`_button.scss`:
```scss
button {
  color: red;
}
```

Any changes to `_button.scss` will not trigger a reload.
